name    = Dancer2-Serializer-Dumper
author  = Dancer Core Developers
license = Perl_5
copyright_holder = Alexis Sukrieh
copyright_year   = 2021

[@Basic]

; Versioning - Git::NextVersion bumps from the last git tag, by default,
; unless `V=` is used.  OurPkgVersion stamps that version in place of # VERSION
; lines.  Git::Tag tags the release after.
[Git::NextVersion]
[OurPkgVersion]
[Git::Tag]

filename = Changes

[AutoPrereqs]

[Prereqs]
Moo = 0
Dancer2 = 0

[MetaResources]
homepage        = http://perldancer.org/
bugtracker.web  = https://github.com/PerlDancer/Dancer2-Serializer-Dumper/issues
repository.url  = git://github.com/PerlDancer/Dancer2-Serializer-Dumper.git
repository.web  = https://github.com/PerlDancer/Dancer2-Serializer-Dumper
repository.type = git
x_IRC           = irc://irc.perl.org/#dancer
x_WebIRC        = https://chat.mibbit.com/#dancer@irc.perl.org

[ReadmeAnyFromPod / MarkdownInRoot]
filename = README.mkdn
